# Day 22: Creating and Slicing Arrays in NumPy


## 1. Different Ways to Create NumPy Arrays

NumPy provides efficient methods to create arrays depending on the data requirement.

### 1.1 Using `np.array()`

Converts Python lists or tuples into NumPy arrays.

In [4]:
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array((7, 8, 9))

print(arr1)
print()
print(arr2)
print()
print(arr3)
print()

[10 20 30 40]

[[1 2 3]
 [4 5 6]]

[7 8 9]



**Key Points:**
- Automatically detects data type
- Supports 1D, 2D, and higher dimensions

**Practice:**
1. Create a 3x3 array using lists
2. Check its shape and dtype

### 1.2 Using `np.zeros()` and `np.ones()`

Used to initialize arrays with default values.

In [8]:
zeros_matrix = np.zeros((3, 4))
ones_array = np.ones(5)

print(zeros_matrix)
print()
print(ones_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[1. 1. 1. 1. 1.]


**Real-world Use:**
- Initializing weights
- Placeholder matrices

**Practice:**
1. Create a 5x5 zero matrix
2. Create a 2x3 ones matrix

### 1.3 Using `np.arange()`

Creates evenly spaced values using a step size.

In [10]:
arr_a = np.arange(0, 20, 2)
arr_b = np.arange(5, 15)

print(arr_a)
print()
print(arr_b)

[ 0  2  4  6  8 10 12 14 16 18]

[ 5  6  7  8  9 10 11 12 13 14]


**Interview Tip:** `arange()` may skip the endpoint due to step size.

**Practice:**
1. Generate numbers from 10 to 100 with step 10
2. Observe output when step is omitted

### 1.4 Using `np.linspace()`

Creates evenly spaced values by specifying total count.

In [12]:
lin1 = np.linspace(0, 1, 5)
lin2 = np.linspace(10, 50, 9)

print(lin1)
print()
print(lin2)

[0.   0.25 0.5  0.75 1.  ]

[10. 15. 20. 25. 30. 35. 40. 45. 50.]


**Difference:**
- `arange()` → step-based
- `linspace()` → count-based

**Practice:**
1. Generate 7 values between 0 and 70

### 1.5 Using `np.eye()`

Creates an identity matrix.

In [14]:
identity_3 = np.eye(3)
identity_5 = np.eye(5)

print(identity_3)
print()
print(identity_5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 1.6 Using `np.random` Module

Used for generating random data for simulations and testing.

In [5]:
import numpy as np 
print('Random Uniform:')
print(np.random.rand(3, 3))
print()

print('Random Normal:')
print(np.random.randn(2, 4))
print()

print('Random Integers:')
print(np.random.randint(10, 50, size=(4, 4)))

Random Uniform:
[[0.08783952 0.84463529 0.09034075]
 [0.05305438 0.76296093 0.73795442]
 [0.85163709 0.76500467 0.59001221]]

Random Normal:
[[ 0.16472487  2.1154904  -0.68416253 -1.19805404]
 [ 0.02636568  0.69539629  0.5344825  -0.66679418]]

Random Integers:
[[30 17 10 39]
 [41 21 15 14]
 [48 18 26 19]
 [43 16 25 37]]


**Practice:**
1. Create a 5x5 random integer matrix between 1 and 100
2. Create a 1D normal distribution array

## 2. Slicing in NumPy Arrays

Slicing extracts portions of arrays efficiently without copying data.

### 2.1 Slicing in 1D Arrays

In [7]:
arr = np.array([5, 10, 15, 20, 25, 30])

print(arr[1:4])
print()
print(arr[:3])
print()
print(arr[::2])
print()
print(arr[-3:])

[10 15 20]

[ 5 10 15]

[ 5 15 25]

[20 25 30]


### 2.2 Slicing in 2D Arrays

In [9]:
arr2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(arr2d[0:2, 1:3])
print()
print(arr2d[:, 2])
print()
print(arr2d[1, :])

[[2 3]
 [6 7]]

[ 3  7 11]

[5 6 7 8]


### 2.3 Step Size & Negative Indexing

In [13]:
print(arr[::-1])
print()
print(arr2d[:, ::-1])

[30 25 20 15 10  5]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


**Practice:**
1. Extract the last row
2. Reverse columns of a matrix

## 3. Speed, Performance, and Memory

### 3.1 NumPy vs Python List Speed Comparison

In [26]:
import time
import numpy as np 

py_list = list(range(1_000_000))
np_array = np.arange(1_000_000)

start = time.time()
[x * 2 for x in py_list]
print('Python list time:', time.time() - start)

start = time.time()
np_array * 2
print('NumPy array time:', time.time() - start)

Python list time: 0.07388472557067871
NumPy array time: 0.002076387405395508


### 3.2 Memory Efficiency of NumPy

- Stores data in contiguous memory
- Less overhead than Python objects
- Faster vectorized operations

### 3.3 Avoiding Unnecessary Copies

In [17]:
a = np.array([10, 20, 30, 40, 50])
b = a[1:4]
b[0] = 999

print('Original array:', a)
print('View array:', b)

Original array: [ 10 999  30  40  50]
View array: [999  30  40]


⚠️ **Important:** Slicing creates views, not copies.

**Interview Question:** How do you create a copy? → `arr.copy()`

## Final Practice & Revision

1. Create a 4x4 identity matrix
2. Generate 12 values between 50 and 150 using linspace
3. Slice the center 2x2 matrix from a 4x4 array
4. Compare speed of addition using list vs NumPy
5. Explain view vs copy with example

