# Day 42: Linear Algebra for Machine Learning – Matrices

In Machine Learning, we never work with single values.
We work with **large datasets**, **multiple features**, and **many outputs**.

To handle all of this efficiently, we use **Matrices**.

In ML:
- Dataset → Matrix
- Model parameters → Matrix
- Predictions → Matrix

That’s why understanding matrices is **mandatory** for Data Science and ML.


## What is a Matrix? (Easy / Lemon Explanation)

Think of an Excel sheet:

Rows → Data points (students, customers, records)  
Columns → Features (marks, age, salary, height)

That full table is called a **Matrix**.

Example:
Marks of students in subjects:

| Math | Science |
|------|---------|
| 70   | 80      |
| 60   | 75      |
| 90   | 85      |

This table itself is a **Matrix**.


## Technical Definition of a Matrix

A **matrix** is a rectangular arrangement of numbers organized into rows and columns.

It is represented as:

A(m × n)

Where:
- m = number of rows
- n = number of columns

Example:

A =  
[ 1  2 ]  
[ 3  4 ]  
[ 5  6 ]

This is a **3 × 2 matrix**.


In [7]:
import numpy as np

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

A

array([[1, 2],
       [3, 4],
       [5, 6]])

## Role of Matrices in Machine Learning

In ML problems:

- Input data (features) → Matrix X
- Model weights → Matrix W
- Output predictions → Matrix Y

ML models internally perform:
X × W = Y

So Machine Learning is basically **matrix operations running repeatedly**.


## Matrix Addition



Imagine:
- Marks before internal exam
- Marks after re-evaluation

You add subject-wise marks.

Same shape → Addition possible  
Different shape → Addition NOT possible


### Technical Rule for Matrix Addition

Two matrices can be added **only if their dimensions are the same**.

A + B = C


In [14]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A + B


array([[ 6,  8],
       [10, 12]])

## Matrix Multiplication (MOST IMPORTANT FOR ML)

### Lemon Explanation

Imagine cooking food:
- Ingredients → Features
- Recipe → Weights

You don’t just add ingredients.
You mix them in specific proportions.

That mixing process is **Matrix Multiplication**.


### Technical Meaning of Matrix Multiplication

Matrix multiplication represents:
- Weighted combination of features
- Transformation of input data

In ML:
X × W = Y

Where:
- X → Input feature matrix
- W → Weight matrix
- Y → Output
- @ -> Matrix multiplication 


In [21]:
X = np.array([[1, 2],
              [3, 4]])

W = np.array([[2],
              [1]])

Y= X @ W
Y


array([[ 4],
       [10]])

## Determinant of a Matrix

### Lemon Explanation

Determinant answers one question:
"Does this matrix collapse information or preserve it?"

If determinant = 0  
→ Information collapses  
→ Inverse is not possible


### Technical Meaning of Determinant

- Determinant tells scaling effect of a matrix
- Used to check:
  - Invertibility
  - Solvability of equations

Only **square matrices** have determinants.
`Only square matrices represent transformations that can be reversed.
Non-square matrices change dimensions, so determinant is not defined.`


In [25]:
A = np.array([[2, 1],
              [4, 2]])

np.linalg.det(A)


0.0

In [ ]:
Matrix = machine

Input goes in

Output comes out

If determinant = 0
→ Machine squashes everything
→ Some information is lost
→ You cannot reverse the process

👉 That’s why inverse is not possible.

In [ ]:
Imagine:

You compress a file

But compression removes some data permanently

Can you get original file back?

❌ No.

👉 That is determinant = 0.

## Inverse of a Matrix

### Lemon Explanation

Inverse means:
"Undo what the matrix has done"

Like:
Forward operation → Matrix  
Reverse operation → Inverse matrix


### Technical Meaning of Inverse

If:
A × A⁻¹ = I

Then:
- A is invertible
- Determinant ≠ 0


In [34]:
A = np.array([[1, 2],
              [3, 4]])

np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Eigenvalues and Eigenvectors (VERY IMPORTANT FOR ML)

### Lemon Explanation

Imagine data points forming a cloud.

Some directions:
- Data spreads a lot → Important
- Data spreads very little → Noise


### Technical Meaning

- Eigenvector → Direction of maximum data spread
- Eigenvalue → Amount of spread in that direction

Used heavily in:
- PCA ---> ` PCA is a technique that keeps important information and removes unnecessary complexity.`
- Dimensionality Reduction
- Noise removal


In [40]:
A = np.array([[4, 2],
              [1, 3]])

values, vectors = np.linalg.eig(A)

values, vectors


(array([5., 2.]),
 array([[ 0.89442719, -0.70710678],
        [ 0.4472136 ,  0.70710678]]))

Imagine:

- You click a photo in 4K resolution
- You send it on WhatsApp
- WhatsApp compresses it

After compression:
- Image size reduces a lot
- Image still looks almost same
- 👉 PCA works like data compression.

## Why Eigen Concepts Matter in Machine Learning

- PCA keeps directions with high eigenvalues
- Drops low-importance directions
- Makes models:
  - Faster
  - More stable
  - Less noisy

This is why Linear Algebra is a backbone of ML.


## Final Summary (Must Remember)

- Matrix = structured data container
- Addition = simple combining
- Multiplication = feature mixing (core ML operation)
- Determinant = information collapse check
- Inverse = undo operation
- Eigenvalues/Eigenvectors = data importance (PCA)
